version: '3'

services:
  react-client:
    depends_on: 
      - express-server
    container_name: react-client
    build:
      context: .
      dockerfile: client/Dockerfile-local
    volumes:
      - './client:/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  
  express-server:
    depends_on: 
      - mysql-database
    container_name: express-server
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
      - './api:/usr/src/app' 
      - '/app/node_modules'
    ports:
      - '3080:3080'
    environment:
      - NODE_ENV=development     
    
  mysql-database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - '3006:3306'
    environment:
      MYSQL_DATABASE: fullstack-application
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root